# Generated by Django 5.2.1 on 2025-05-17 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_job_companyname'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.CharField(default='$0 - $0', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='years_of_experience',
            field=models.CharField(default='0-1 years', max_length=50),
        ),
    ]
